---
conditions: v1
dist: xenial
language: python

git:
  depth: 100

env:
  global:
  - GITHUB_REPO=ShoGinn/SouthwestCheckin

cache:
  pip: true

python:
  - "3.7"
  - "3.8"

before_install:
  - pip install -U pip tox

install:
  - tox --notest

script: tox -v

after_success:
  - pip install -U coveralls
  - coveralls
  - bash <(curl -f https://codecov.io/bash)

stages:
  - Pre-Commit
  - "Build Docs"
  - Test
  - name: "Unstable Deploy"
    if: type NOT IN (cron, pull_request)  # Always run, except if PR or cron
  - name: "PyPI deploy"
    if: tag IS present


jobs:
  fast_finish: true
  include:
  - stage: Pre-Commit
    name: Checking pre-commit linter compliance
    python: "3.8"
    after_success: skip
    env:
      TOXENV: pre-commit
  - stage: "Build Docs"
    name: "Checking docs build"
    env:
      TOXENV: build-docs
    python: "3.8"
    after_success: skip

  - stage: "Unstable Deploy"
    python: "3.8"
    after_success: echo "Skipping it to deploy"
    env:
      TOXENV: build-dists,metadata-validation
    before_deploy:
    - echo > setup.py
    deploy:
      - provider: pypi
        skip-cleanup: true
        user: __token__
        password:
          secure: >
            JYJXGwsgrKkh7cjgjngdQ5U+MiX9Q5nENBBNYlwsNz+UrmmkvOnxJRJ5I+1HW0hem3MGsL3y6p9a8Xp71CSY0QP4aUoxf21YNUUg3/VCBw/Fj4rm3f/Szs6cl/lA3GlDIJkpowQa9H9MdSNbysI7WnC25KXOCpBe23rMRc+ZCHDRV9IUTIdeYUnAWK32yunjdKtQ34KmY9cIDsfr6gWa1J2lDChHmriCnzXb4EIEZc/t/1zbYAnb3l4jDhgEXuRWR66gPpvKFm3YpJl9sCkuGmgJZz7CN0wB9UmTcKWJ1dxmGivBkbjJCOsGaCBEaBYLFMI+e42EEtFOArEhHQ1r8GdtDe6oOGTixc3Mt786Vudb+TVf7Sc1XrHIwNaTVrPUUA/vOs5X7GamZ8NqXoJl/H6tRVHuKG2Sf8KH1N59LJZK5/fKZBgzkBVcWJC/uCvO59b0I9RFvLQGAoYNx4FGqgV+gXk748yW/+3Mt9ps0apX9Xo1guTCjDNZmG0UwPe7wnNsOy3StLzUr92f5mZzxXK9WThPP0Xq29yhSi7ZeRHQ6Ubc65goBjyDKKPBHbejDF3wbTxOwkPQ5BAejaBLfXBqyySN4cLsZ1JL2xXhKlGKa4c7O2CiXmeRPHbNzH2yqr0PWS8jFpWBSHbY3omyxlW42oW0B7uBUQtEBciqEUI=
        distributions:
        server: https://test.pypi.org/legacy/
        on:
          repo: $GITHUB_REPO

  - stage: "PyPI deploy"
    if: type NOT IN (cron, pull_request)  # Always run, except if PR or cron
    python: "3.8"
    after_success: echo "Skipping it to deploy"
    env:
      TOXENV: build-dists,metadata-validation
    before_deploy:
    - echo > setup.py
    deploy:
      - provider: pypi
        skip-cleanup: true
        user: __token__
        password:
          secure: >
            F4cigrn+m3P0Szovc0nXLeDuC49+oniHVuWjYIWaNedai41t87DdgzjCwm7DCj5pkqliCGrVBNmakEm+Bof24ElZx6ip+hooWqTfZbdb2A/d5WVLnUXnElVUzcFuqXhAVbD8KR+H5xC5cJgjKA5FunqrmV3WcDzG4r0xbMGzLMNqRtk5qUZObaKKRkvMy9IG7+RRUwxgRUfGVZEuDHFONqeJ0y3D/IJvcC943GPDWdwRivzYU2LIhImjCMjQNeJzyzqWFv2eqRyQ3rjEfI1pxj0Va4/5VgYNbl9F1n5pdJfr6kedezKYqt39jLd94N50bPPRNcEUfwEMiexQ6T/ZUw2MPswh1AdXCHUBWbks5PV0CcW/sNxnhmjZVJWliAupFCAyCBdWyNDzK1TJ2AxZx+JK2gMe8xLLO+lQhBAp/JMkndw/o31SN+1Tifi8gvvvNVaBOnmEuxXF3fFL+ZxPAbS6s54E9HnHk49t4RsVsv7OD49MxVMWeJLGJXo/9i6LxhaqgLxSJWQi2Da1PKDreHTBZ+/1qLYvFr5kNBUceTu3gFdlsoZ7L7vUEsK0qcd+hoLdHX3yqYsvMfYQ4nHL0cRzbaZOdR8sQ/YvGUSZgyWf9intYi1X3/3sx/yjBiMagJQ56VTHnC2VkvZZ3dLn+vi8Ccfqrj4S0fwS/s14ZUg=
        distributions:
        on:
          repo: $GITHUB_REPO
          tags: true
          branch: master
